FROM alpine:3.9 AS compile-image

# Add requirements for python and pip
RUN apk add --update python3

# Install dependencies
RUN apk add python3-dev build-base gcc linux-headers mysql-dev libffi-dev

# Create a virtual environment for all the Python dependencies
RUN python3 -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"
RUN pip3 install --upgrade pip

# Install other dependencies
COPY requirements.txt /opt/
RUN pip3 install -r /opt/requirements.txt


FROM alpine:3.9 AS runtime-image

# Add requirements for python and pip
RUN apk add --update python3 libffi mysql-dev

# Copy the venv with compile dependencies from the compile-image
COPY --from=compile-image /opt/venv /opt/venv

# Be sure to activate the venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy the code
COPY . /opt/code/

# Copy uWSGI configuration
RUN mkdir -p /opt/uwsgi
ADD uwsgi/uwsgi.ini /opt/uwsgi/

# Create a user to run the service
RUN addgroup -S uwsgi
RUN adduser -H -D -S uwsgi

# Run parameters
WORKDIR /opt/code

#CMD ["python", "manage.py", "runserver", "0:8000"]
EXPOSE 5000
CMD uwsgi --ini /opt/uwsgi/uwsgi.ini 
